/*
  Student ID: 1155173751
  Name: Chen Yingxin
*/

/* Query 1 */
Spool result1.lst
SELECT L.LID, L.LEAGUE_NAME, R.REGION_NAME, L.YEAR
FROM LEAGUES L
JOIN REGIONS R ON L.RID = R.RID
WHERE L.SEASON IN ('Spring', 'Summer')
ORDER BY L.LID ASC;
Spool off

/* Query 2 */
Spool result2.lst
SELECT T.TID, T.TEAM_NAME, T.AVERAGE_AGE
FROM TEAMS T
JOIN LEAGUES L ON T.TID = L.CHAMPION_TID
WHERE L.SEASON = 'Autumn' AND L.YEAR >= 2015
GROUP BY T.TID, T.TEAM_NAME, T.AVERAGE_AGE
HAVING COUNT(*) > 1
ORDER BY T.TID ASC;
Spool off

/* Query 3 */
Spool result3.lst
SELECT T.TID, T.TEAM_NAME, T.AVERAGE_AGE, L.SEASON, W_NUM
FROM (
    SELECT CHAMPION_TID, SEASON, COUNT(*) AS W_NUM,
           RANK() OVER (PARTITION BY SEASON ORDER BY COUNT(*) DESC) AS rank_num
    FROM LEAGUES
    GROUP BY CHAMPION_TID, SEASON
) L
JOIN TEAMS T ON T.TID = L.CHAMPION_TID
WHERE L.rank_num = 1
ORDER BY T.TID ASC, L.SEASON ASC;
Spool off

/* Query 4 */
Spool result4.lst
SELECT SID, SPONSOR_NAME, L_NUM
FROM (
    SELECT S.SID, S.SPONSOR_NAME, COUNT(*) AS L_NUM
    FROM SPONSORS S
    JOIN SUPPORT SP ON S.SID = SP.SID
    GROUP BY S.SID, S.SPONSOR_NAME
    ORDER BY L_NUM DESC
)
ORDER BY SID ASC
FETCH FIRST 5 ROWS ONLY;
Spool off

/* Query 5 */
Spool result5.lst
SELECT L.LID, L.LEAGUE_NAME
FROM LEAGUES L
JOIN SUPPORT SP ON L.LID = SP.LID
JOIN SPONSORS S ON SP.SID = S.SID
JOIN TEAMS T ON L.CHAMPION_TID = T.TID
WHERE L.SEASON IN ('Autumn', 'Winter')
AND S.MARKET_VALUE > 50
AND T.AVERAGE_AGE < 30
GROUP BY L.LID, L.LEAGUE_NAME
ORDER BY L.LID DESC;
Spool off

/* Query 6 */
Spool result6.lst
SELECT SID, HOT
FROM (
    SELECT S.SID,
        (SUM(SS.SPONSORSHIP) / (SQRT(S.MARKET_VALUE) * LOG(SQRT(R.FOOTBALL_RANKING) + 1, 2))) AS HOT,
        ROW_NUMBER() OVER (PARTITION BY S.SID ORDER BY S.SID DESC) AS RN
    FROM SPONSORS S
    JOIN SUPPORT SS ON S.SID = SS.SID
    JOIN LEAGUES L ON SS.LID = L.LID
    JOIN REGIONS R ON L.RID = R.RID
    WHERE S.MARKET_VALUE > 40 AND R.FOOTBALL_RANKING < 10
    GROUP BY S.SID, S.MARKET_VALUE, SQRT(R.FOOTBALL_RANKING)
    ORDER BY S.SID DESC
)
WHERE RN = 1
ORDER BY SID DESC;
Spool off

/* Query 7 */
Spool result7.lst
SELECT
    RID,
    MAX(CASE WHEN SID = 4 THEN HOT ELSE NULL END) AS HOT_4,
    MAX(CASE WHEN SID = 5 THEN HOT ELSE NULL END) AS HOT_5,
    MAX(CASE WHEN SID = 6 THEN HOT ELSE NULL END) AS HOT_6,
    MAX(CASE WHEN SID = 7 THEN HOT ELSE NULL END) AS HOT_7,
    GREATEST(NVL(MAX(CASE WHEN SID = 4 THEN HOT ELSE NULL END), 0),
             NVL(MAX(CASE WHEN SID = 5 THEN HOT ELSE NULL END), 0),
             NVL(MAX(CASE WHEN SID = 6 THEN HOT ELSE NULL END), 0),
             NVL(MAX(CASE WHEN SID = 7 THEN HOT ELSE NULL END), 0)) AS HOT_HIGH
FROM (
    SELECT R.RID, S.SID,
        (SUM(SS.SPONSORSHIP) / (SQRT(S.MARKET_VALUE) * LOG(SQRT(R.FOOTBALL_RANKING) + 1, 2))) AS HOT
    FROM SPONSORS S
    JOIN SUPPORT SS ON S.SID = SS.SID
    JOIN LEAGUES L ON SS.LID = L.LID
    JOIN REGIONS R ON L.RID = R.RID
    WHERE S.SID IN (4, 5, 6, 7)
    GROUP BY R.RID, S.SID, S.MARKET_VALUE, SQRT(R.FOOTBALL_RANKING)
)
GROUP BY RID
ORDER BY RID DESC;
Spool off

/* Query 8 */
Spool result8.lst
SELECT DISTINCT S.SID, S.SPONSOR_NAME
FROM SPONSORS S
JOIN SUPPORT SP ON S.SID = SP.SID
JOIN LEAGUES L ON SP.LID = L.LID
JOIN (
    SELECT CHAMPION_TID, COUNT(*) AS NUM_WINS
    FROM LEAGUES
    GROUP BY CHAMPION_TID
    HAVING COUNT(*) = (
        SELECT MAX(COUNT(*))
        FROM LEAGUES
        GROUP BY CHAMPION_TID
    )
) T ON L.CHAMPION_TID = T.CHAMPION_TID
ORDER BY S.SID ASC;
Spool off
